name: Release

description: Release packages

inputs:
  git_bot_token:
    description: Git bot token
    required: true
  npm_token:
    description: NPM token
    required: true

runs:
  using: composite
  steps:
    - name: Release
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
        GITHUB_TOKEN: ${{ inputs.git_bot_token }}
      # Use npx instead of yarn because yarn automagically sets NPM_* environment variables
      # like NPM_CONFIG_REGISTRY so npm publish ends up ignoring the .npmrc file
      # which is set up by `setup-node` action.
      shell: bash
      run: npx nx release --yes

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.git_bot_token }}
        branch: ${{ github.ref }}
        force: true
        tags: true
